"""
Pydantic models for validation and documentation - TrustLedger Ecosystem
"""
from pydantic import BaseModel, Field, field_validator, validator
from typing import List, Optional, Any, Dict
import re


class VoiceTransaction(BaseModel):
    item: str = Field(..., description="The name of the item sold or expense incurred")
    amount: float = Field(..., gt=0, description="The cost in Naira (must be positive)")
    quantity: int = Field(default=1)
    unit: str = Field(default="item", description="The unit of the item (e.g., 'kg', 'piece', bag, derica, paint, kg)")
    type: str = Field(..., pattern="^(SALE|EXPENSE|SUPPLIER_PAYMENT|CASUAL_LABOR_PAYOUT|LOGISTICS_DELIVERY)$")
    timestamp: Optional[str] = None
    notes: Optional[str] = "No additional notes"
    
    # OPay-specific transactional cross-references
    opay_order_no: Optional[str] = Field(None, description="The official tracking reference generated by OPay server")
    payment_reference: Optional[str] = Field(None, description="Internal custom reference string (e.g., REF-109283)")
    product_id: Optional[str] = Field(None, description="Associated product inventory identification if matching a static QR scan")
    associated_phone: Optional[str] = Field(None, description="The OPay wallet phone number of the target worker or supplier paid")

    verified: bool = False # Default to False until verified by Squad
    is_anomaly: bool = False # Flag for potential fraud or errors, set by backend logic

    @field_validator('amount', pre=True)
    def ensure_float_amount(cls, v):
        # In case the AI sends "5000" instead of 5000
        if isinstance(v, str):
            # Strip NGN, commas, and handle 'k'
            clean_v = v.upper().replace("NGN", "").replace("NAIRA", "").replace(",", "").strip()
            clean_v = re.sub(r'[^\d\.Kk]', '', clean_v) # Remove any non-numeric, non-dot, non-K characters
            if 'K' in clean_v:
                try:
                    result = float(clean_v.replace("K", "")) * 1000
                    return result
                except ValueError:
                    return 0.0 # Default to 0.0 if we can't parse it

            try:
                return float(clean_v)
            except ValueError:
                return float(v) if v else 0.0

        try:
            return float(v)
        except (TypeError, ValueError):
            return 0.0
            
    @field_validator('quantity', pre=True)
    def ensure_int_quantity(cls, v):
        """Ensures quantity is a clean integer, even if AI sends strings or floats."""
        if isinstance(v, str):
            try:
                # Handle common textual numbers (Optional: add a dict for 'one','two', etc. if needed)
                clean_v = v.strip().split()[0] # Take first part in case of "5 units"
                return int(float(clean_v))
            except (ValueError, TypeError):
                return 1 # Default to 1 if we can't parse it
        if isinstance(v, float):
            return int(v)
        return v
    

class VoiceProcessResponse(BaseModel):
    status: str
    transaction: Optional[VoiceTransaction] = None
    message: Optional[str] = None

class OCRProcessResponse(BaseModel):
    """Response model for OCR processing"""
    status: str
    extracted_data: Dict[str, Any]
    image_text: str

class LocationSchema(BaseModel):
    city: str
    state: str
    country: str = "Nigeria"


class TierInfo(BaseModel):
    name: str
    color: str
    next_milestone: int


class UserCreate(BaseModel):
    id: str
    name: str
    email: str # Added email
    password: str # Added password
    role: str = Field(..., pattern="^(Merchant|Agent|Supplier)$")
    location: LocationSchema


class UserProfile(BaseModel):
    id: str = Field(..., description="Unique ID")
    name: str
    email: str
    role: str = Field(..., pattern="^(Merchant|Agent|Supplier)$")
    location: LocationSchema
    trust_score: int = 50
    tier: TierInfo


class DashboardResponse(BaseModel):
    profile: UserProfile
    recent_transactions: list[VoiceTransaction]


# Response and Request models for Squad routes

class ErrorResponse(BaseModel):
    status: str = "error"
    message: str
    code: Optional[int] = None
    details: Optional[Any] = None


class VirtualAccountRequest(BaseModel):
    merchant_id: str
    business_name: str
    first_name: str = None
    last_name: str = None
    email: str
    phone: str

    @field_validator('phone')
    def validate_nigerian_phone(cls, v):
        # Basic regex for Nigerian phone numbers (starts with +234 or 0, followed by 10 digits)
        pattern = r'^(\+234|0)[789][01]\d{8}$'
        if not re.match(pattern, v):
            raise ValueError('Invalid Nigerian phone number format')
        return v.strip()


class VirtualAccountResponse(BaseModel):
    status: str
    account_number: str
    bank_name: str = "Opay Microfinance Bank"
    merchant_id: str
    business_name: str


class ProductQRRequest(BaseModel):
    """Triggered when a merchant generates a static visual payment link card for a specific recurring market asset"""
    merchant_id: str
    product_name: str
    price: float
    description: Optional[str] = "Fixed Price Product QR"


class ProductQRResponse(BaseModel):
    status: str
    product_id: str
    merchant_id: str
    price: float
    # The actual ISO string payload that the frontend uses to draw the QR block on screen
    qr_code_payload: str  
    payment_reference: str


class OPayWebhookPayload(BaseModel):
    """
    The secure backend JSON scheme used when OPay's background payment infrastructure 
    notifies our FastAPI listener that an invoice or product QR has been successfully settled by a customer.
    """
    event: str = Field(..., description="e.g., payment.success or ORDER_COMPLETED")
    orderNo: str = Field(..., description="The unique OPay core execution number")
    reference: str = Field(..., description="Our internal application custom tracking reference string")
    amount: Dict[str, Any] = Field(..., description="OPay structured asset amount object, e.g. {'currency': 'NGN', 'total': 80000}")
    status: str = Field(..., description="Final balance lifecycle state: SUCCESS, FAIL")


class CasualLaborPayoutRequest(BaseModel):
    """Fired when a merchant issues an outbound payment straight to a logistics provider (barrow pusher, delivery rider)"""
    merchant_id: str
    worker_phone: str = Field(..., description="Target target phone number acting as their OPay transfer endpoint")
    amount: float
    narration: Optional[str] = "TrustLedger Logistics Payout"


class FlashNotificationPayload(BaseModel):
    """
    Schema passed over our active WebSocket pipeline to fire real-time overlay notifications 
    on the user interface whenever a payment settles, without requiring page refreshes.
    """
    type: str = "PAYMENT_FLASH"
    title: str = "Payment Confirmed!"
    message: str  # e.g., "Received ₦80,000 from Segun Alao via Access Bank Scan"
    reference: str
    amount: float

class ChatRequest(BaseModel):
    message: str | None = None
    voice_path: str | None = None