"""
Pydantic models for validation and documentation - TrustLedger Ecosystem
"""
from pydantic import BaseModel, Field, field_validator
from typing import List, Optional, Any, Dict
import re


class TransactionRequest(BaseModel):
    item: str = Field(..., description="The name of the item sold or expense incurred")
    amount: float = Field(..., gt=0, description="The cost in Naira (must be positive)")
    quantity: int = Field(default=1)
    unit: str = Field(default="item", description="The unit of the item (e.g., 'kg', 'piece', bag, derica, paint)")
    type: str = Field(..., pattern="^(SALE|EXPENSE|SUPPLIER_PAYMENT|CASUAL_LABOR_PAYOUT|LOGISTICS_DELIVERY)$")
    timestamp: Optional[str] = None
    notes: Optional[str] = "No additional notes"
    
    # OPay-specific transactional cross-references
    opay_order_no: Optional[str] = Field(None, description="The official tracking reference generated by OPay server")
    payment_reference: Optional[str] = Field(None, description="Internal custom reference string (e.g., REF-109283)")
    product_id: Optional[str] = Field(None, description="Associated product inventory identification if matching a static QR scan")
    associated_phone: Optional[str] = Field(None, description="The OPay wallet phone number of the target worker or supplier paid")

    verified: bool = False  # Default to False until verified by background webhooks
    is_anomaly: bool = False  # Flag for potential fraud or errors, set by backend logic

    @field_validator('amount', mode='before')
    @classmethod
    def ensure_float_amount(cls, v):
        """Standardizes messy input strings (like 'NGN 5,000' or '2.5k') into clean floats."""
        if isinstance(v, str):
            clean_v = v.upper().replace("NGN", "").replace("NAIRA", "").replace(",", "").strip()
            clean_v = re.sub(r'[^\d\.Kk]', '', clean_v)
            if 'K' in clean_v:
                try:
                    return float(clean_v.replace("K", "")) * 1000.0
                except ValueError:
                    return 0.0

            try:
                return float(clean_v)
            except ValueError:
                return float(v) if v.isdigit() else 0.0

        try:
            return float(v)
        except (TypeError, ValueError):
            return 0.0
            
    @field_validator('quantity', mode='before')
    @classmethod
    def ensure_int_quantity(cls, v):
        """Ensures quantity is a clean integer, even if AI sends unstructured text or floats."""
        if isinstance(v, str):
            try:
                clean_v = v.strip().split()[0]
                return int(float(clean_v))
            except (ValueError, TypeError):
                return 1  # Graceful fallback for non-numeric voice strings like 'a bag'
        if isinstance(v, (int, float)):
            return int(v)
        return v
    

class VoiceProcessResponse(BaseModel):
    status: str
    transaction: Optional[TransactionRequest] = None
    message: Optional[str] = None


class OCRProcessResponse(BaseModel):
    """Response model for OCR processing"""
    status: str
    extracted_data: Dict[str, Any]
    image_text: str


class LocationSchema(BaseModel):
    city: str
    state: str
    country: str = "Nigeria"


class TierInfo(BaseModel):
    name: str
    color: str
    next_milestone: int

class UserProfile(BaseModel):
    """
    Standard profile representation for profile updates, dependency injections,
    and single-user configuration endpoints.
    """
    id: str = Field(..., description="The verified Firebase unique identifier (UID)")
    name: str
    email: str
    role: str = Field(..., pattern="^(Merchant|Agent|Supplier)$")
    location: Optional[LocationSchema] = None
    trust_score: int = Field(43, description="Calculated systemic reputation index")
    tier: Optional[TierInfo] = None

    class Config:
        populate_by_name = True


class UserProfileUpdateRequest(BaseModel):
    """Used when a user wants to modify their profile data from the mobile/web application."""
    name: Optional[str] = None
    location: Optional[LocationSchema] = None

class UserCreate(BaseModel):
    id: str
    name: str
    email: str 
    password: str 
    role: str = Field(..., pattern="^(Merchant|Agent|Supplier)$")
    location: LocationSchema


class DashboardResponse(BaseModel):
    """Matches the precise flat data layout returned by GraphService.get_user_dashboard."""
    name: str
    trust_score: int = Field(50, alias="score")
    role: str
    city: str
    state: str
    country: str
    tier: TierInfo
    transactions: List[TransactionRequest]

    class Config:
        populate_by_name = True


# Response and Request models for Squad/OPay gateway processing routes
class ErrorResponse(BaseModel):
    status: str = "error"
    message: str
    code: Optional[int] = None
    details: Optional[Any] = None


class VirtualAccountRequest(BaseModel):
    merchant_id: str
    business_name: str
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    email: str
    phone: str

    @field_validator('phone')
    @classmethod
    def validate_nigerian_phone(cls, v):
        """Enforces clean structural phone tracking patterns before passing data downstream."""
        pattern = r'^(\+234|0)[789][01]\d{8}$'
        if not re.match(pattern, v.strip()):
            raise ValueError('Invalid Nigerian phone number format. Must start with +234 or 0.')
        return v.strip()


class VirtualAccountResponse(BaseModel):
    status: str
    account_number: str
    bank_name: str = "Opay Microfinance Bank"
    merchant_id: str
    business_name: str


class ProductQRRequest(BaseModel):
    """Triggered when a merchant generates a static visual payment link card for an asset."""
    merchant_id: str
    product_name: str
    price: float
    description: Optional[str] = "Fixed Price Product QR"


class ProductQRResponse(BaseModel):
    status: str
    product_id: str
    merchant_id: str
    price: float
    qr_code_payload: str  
    payment_reference: str


class OPayWebhookPayload(BaseModel):
    """OPay incoming webhook tracking object schema."""
    event: str = Field(..., description="e.g., payment.success or ORDER_COMPLETED")
    orderNo: str = Field(..., description="The unique OPay core execution number")
    reference: str = Field(..., description="Our internal application custom tracking reference string")
    amount: Dict[str, Any] = Field(..., description="Structured currency mapping, e.g. {'currency': 'NGN', 'total': 80000}")
    status: str = Field(..., description="Final balance lifecycle state: SUCCESS, FAIL")


class CasualLaborPayoutRequest(BaseModel):
    """Fired when a merchant issues an outbound payment straight to a logistics provider."""
    merchant_id: str
    worker_phone: str = Field(..., description="Target phone number acting as their transfer endpoint")
    amount: float
    narration: Optional[str] = "TrustLedger Logistics Payout"


class FlashNotificationPayload(BaseModel):
    """Real-time active WebSocket message payload schema."""
    type: str = "PAYMENT_FLASH"
    title: str = "Payment Confirmed!"
    message: str  
    reference: str
    amount: float


class ChatRequest(BaseModel):
    message: Optional[str] = None
    voice_path: Optional[str] = None
